# -*- coding: utf-8 -*-
"""DC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BBra2gSgfm2b9OF2IqQZynD1f8pyb1ct

# Загрузка данных
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

df = pd.read_csv("Hotel Reservations.csv")

print("\n=== ПОИСК АНОМАЛИЙ ===")
def quick_audit(df):
    report = {
        'Срок бронирования > 1 год': (df['lead_time'] > 365).sum(),
        'Дети без взрослых': ((df['no_of_adults'] == 0) & (df['no_of_children'] > 0)).sum(),
        'Брони без гостей': (df['no_of_adults'] + df['no_of_children'] == 0).sum(),
        'Отрицательные ночи': ((df['no_of_weekend_nights'] < 0) | (df['no_of_week_nights'] < 0)).sum()
    }
    return report

print("\n🔍 Отчёт об аномалиях:")
for issue, count in quick_audit(df).items():
    print(f"• {issue}: {count}")

"""# Фильтрация бронирований: исключение долгих lead_time и смешанных групп (взрослые + дети)"""

df = df[df['lead_time'] <= 365]
df = df[~((df['no_of_adults'] != 0) & (df['no_of_children'] > 0))]
df

"""# Проверка и обработка пропусков"""

print("\n=== ПРОВЕРКА И ОБРАБОТКА ПРОПУСКОВ ===")
missing = df.isnull().sum()
if missing.sum() == 0:
    print("✓ Пропуски отсутствуют")
else:
    print("Найдены пропуски в столбцах:")
    display(missing[missing > 0])

numeric_cols = ['lead_time', 'no_of_adults', 'no_of_children',
                   'no_of_weekend_nights', 'no_of_week_nights']
categorical_cols = ['type_of_meal_plan', 'room_type_reserved', 'market_segment_type']

"""# Проверка временных аномалий"""

print("\n=== ПРОВЕРКА ВРЕМЕННЫХ АНОМАЛИЙ ===")
current_year = pd.Timestamp.now().year
time_issues = {
    'Брони из будущего': (df['arrival_year'] > current_year).sum(),
}
price_issues = {
    'Цена номера <= 0': (df['avg_price_per_room'] <= 0).sum(),
    'Цена > 99% перцентиля': (df['avg_price_per_room'] > df['avg_price_per_room'].quantile(0.99)).sum()
}

print("\n📊 Расширенный отчёт:")
print("Временные аномалии:")
for issue, count in time_issues.items():
    print(f"• {issue}: {count}")

print("\nЦеновые аномалии:")
for issue, count in price_issues.items():
    print(f"• {issue}: {count}")

"""# Средняя цена номера"""

df = df[df['avg_price_per_room'] > 0]
df = df[df['avg_price_per_room'] < df['avg_price_per_room'].quantile(0.99)]
df

"""# Статистика, типы данных и пропуски"""

print("\n=== ОБЗОР ДАННЫХ ===")

print("\nОсновные статистики:")
desc = df.describe(include='all')
pd.options.display.float_format = '{:.2f}'.format
with pd.option_context('display.max_columns', 10):
    display(desc)

print("\nТипы данных и пропущенные значения:")
print(df.info())

print("\nКоличество пропущенных значений:")
missing_values = df.isnull().sum()
print(missing_values.to_string())

print("\nКоличество дубликатов строк:", df.duplicated().sum())

cat_cols = ['type_of_meal_plan', 'room_type_reserved', 'market_segment_type', 'booking_status']
for col in cat_cols:
    print(f"\nКолонка: {col}")
    print(df[col].unique()[:5])

"""# Анализ числовых переменных"""

print("\n=== АНАЛИЗ ЧИСЛОВЫХ ПЕРЕМЕННЫХ ===")

print("\nГистограммы распределений:")
plt.style.use('default')
axes = df.hist(
    figsize=(20, 15),
    bins=20,
    grid=False,
    color='#ab1636',
    edgecolor='white',
    linewidth=1,
    zorder=2
)
plt.suptitle("Распределение числовых признаков", y=1, fontsize=20, fontweight='bold')
for ax in axes.flatten():
    for spine in ['top', 'right']:
        ax.spines[spine].set_visible(False)
    ax.set_xlabel('Значения', fontsize=12, labelpad=10)
    ax.set_ylabel('Количество', fontsize=12, labelpad=10)
    ax.set_title(ax.get_title(), fontsize=14, pad=10)
plt.tight_layout()
plt.show()

# После гистограмм добавляем боксплоты с выбросами
print("\nАнализ выбросов:")
num_cols = ['lead_time', 'no_of_weekend_nights', 'no_of_week_nights', 'avg_price_per_room']
plt.figure(figsize=(12, 6))
sns.boxplot(
    data=df[num_cols],
    palette=['#ab1636']*len(num_cols),
    width=0.5,
    flierprops=dict(marker='o', markersize=5, markerfacecolor='#3a7ca5')  # Выбросы синим
)
plt.title("Распределение числовых признаков (с выбросами)", fontsize=14, pad=15)
plt.xticks(rotation=45)
plt.show()

for col in num_cols:
    q1, q3 = df[col].quantile([0.25, 0.75])
    iqr = q3 - q1
    lower, upper = q1 - 1.5*iqr, q3 + 1.5*iqr
    outliers = df[(df[col] < lower) | (df[col] > upper)]
    print(f"\n{col}:")
    print(f"• Границы выбросов: [{lower:.1f}, {upper:.1f}]")
    print(f"• Найдено выбросов: {len(outliers)} ({len(outliers)/len(df)*100:.1f}%)")

print("\nАнализ времени бронирования:")
plt.figure(figsize=(10, 5))
sns.boxplot(
    x=df['lead_time'],
    color='#ab1636',
    width=0.3,
    linewidth=0.5,
    flierprops=dict(marker='o', markersize=3)
)
plt.title(
    "Распределение времени между бронированием и заездом",
    fontsize=14,
    fontweight='bold',
    pad=15
)
plt.xlabel(
    "Дней",
    fontsize=12,
    labelpad=10
)
ax = plt.gca()
ax.set_facecolor('white')
for spine in ['top', 'right']:
    ax.spines[spine].set_visible(False)
plt.tight_layout()
plt.show()

print("\nДополнительные распределения:")
num_cols = ['no_of_adults', 'no_of_children', 'no_of_weekend_nights', 'no_of_week_nights', 'avg_price_per_room']
plt.figure(figsize=(15, 8))
sns.boxplot(
    data=df[num_cols],
    palette=['#ab1636']*len(num_cols),
    width=0.5,
    linewidth=0.7
)
plt.title("Распределение ключевых числовых параметров", fontsize=16, pad=15)
plt.xticks(rotation=45)
ax = plt.gca()
ax.set_facecolor('white')
for spine in ['top', 'right']:
    ax.spines[spine].set_visible(False)
plt.tight_layout()
plt.show()

print("\n=== АНАЛИЗ КАТЕГОРИАЛЬНЫХ ПЕРЕМЕННЫХ ===")

plt.figure(figsize=(10, 4))
sns.countplot(
    x='type_of_meal_plan',
    data=df,
    order=df['type_of_meal_plan'].value_counts().index,
    color='#ab1636',
    edgecolor='white',
    linewidth=0.5
)
plt.title("Распределение типов питания", fontsize=14, fontweight='bold', pad=15)
plt.xlabel("Тип питания", fontsize=12, labelpad=10)
plt.ylabel("Количество бронирований", fontsize=12, labelpad=10)
plt.xticks(rotation=45)
ax = plt.gca()
ax.set_facecolor('white')
for spine in ['top', 'right']:
    ax.spines[spine].set_visible(False)
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 4))
sns.countplot(
    x='type_of_meal_plan',
    hue='booking_status',
    data=df,
    palette=['#ab1636', '#3a7ca5'],
    edgecolor='white',
    linewidth=0.5
)
plt.title("Тип питания vs Статус бронирования", fontsize=14, fontweight='bold', pad=15)
plt.xlabel("Тип питания", fontsize=12, labelpad=10)
plt.ylabel("Количество бронирований", fontsize=12, labelpad=10)
plt.xticks(rotation=45)
plt.legend(title='Статус брони', title_fontsize=12, fontsize=11)
ax = plt.gca()
ax.set_facecolor('white')
for spine in ['top', 'right']:
    ax.spines[spine].set_visible(False)
plt.tight_layout()
plt.show()

print("\nПроцентное соотношение статусов брони по типам питания:")
crosstab = pd.crosstab(
    index=df['type_of_meal_plan'],
    columns=df['booking_status'],
    normalize='index'
).round(2) * 100
display(crosstab.style
        .set_caption("Таблица соотношения (в %)")
        .set_properties(**{'background-color': 'white', 'color': '#333333', 'border-color': 'white'})
        .format("{:.0f}%"))

# В блоке "АНАЛИЗ КАТЕГОРИАЛЬНЫХ ПЕРЕМЕННЫХ"
print("\nПроверка аномалий в основных категориальных признаках:")
for col in ['type_of_meal_plan', 'room_type_reserved', 'market_segment_type']:
    print(f"\n• {col}:")
    display(df[col].value_counts(dropna=False).to_frame().style.set_caption(f"Распределение {col}"))

### Ключевые наблюдения:
# - **Тип питания:** Meal Plan 1 встречается в 60% бронирований.
# - **Каналы бронирования:** 72% через онлайн-каналы.
# - **Корреляция:** Срок бронирования (`lead_time`) и отмены (+0.45).

print("\n=== АНАЛИЗ КАТЕГОРИАЛЬНЫХ ПЕРЕМЕННЫХ ===")

plt.figure(figsize=(8, 8))
df['room_type_reserved'].value_counts().plot.pie(
    autopct='%1.1f%%',
    colors=['#ab1636', '#d92b4b', '#f26a8d', '#ff9bb3', '#c5e0f9', '#8cb9e8', '#5a8fd3'],
    wedgeprops={'edgecolor': 'white', 'linewidth': 0.5},
    textprops={'fontsize': 12}
)
plt.title("Доля типов номеров", fontsize=16, fontweight='bold', pad=20)
plt.ylabel('')
plt.tight_layout()
plt.show()

plt.figure(figsize=(12, 5))
sns.countplot(
    x='room_type_reserved',
    hue='booking_status',
    data=df,
    palette=['#ab1636', '#3a7ca5'],
    edgecolor='white',
    linewidth=0.5
)
plt.title("Статус брони по типам номеров", fontsize=16, fontweight='bold', pad=15)
plt.xlabel("Тип номера", fontsize=12, labelpad=10)
plt.ylabel("Количество бронирований", fontsize=12, labelpad=10)
plt.xticks(rotation=45)
plt.legend(title='Статус брони', title_fontsize=12, fontsize=11)
ax = plt.gca()
ax.set_facecolor('white')
for spine in ['top', 'right']:
    ax.spines[spine].set_visible(False)
plt.tight_layout()
plt.show()

print("\nПроцентное соотношение статусов брони по типам номеров:")
crosstab = pd.crosstab(
    index=df['room_type_reserved'],
    columns=df['booking_status'],
    normalize='index'
).round(3) * 100

display(crosstab.style
        .set_caption("Таблица соотношения статусов (в %)")
        .set_properties(**{'background-color': 'white', 'color': '#333333'})
        .format("{:.1f}%"))

print("\n=== АНАЛИЗ КАТЕГОРИАЛЬНЫХ ПЕРЕМЕННЫХ ===")

plt.figure(figsize=(10, 4))
sns.countplot(
    x='market_segment_type',
    data=df,
    order=df['market_segment_type'].value_counts().index,
    color='#ab1636',
    edgecolor='white',
    linewidth=0.5
)
plt.title("Распределение каналов бронирования", fontsize=14, fontweight='bold', pad=15)
plt.xlabel("Канал бронирования", fontsize=12, labelpad=10)
plt.ylabel("Количество бронирований", fontsize=12, labelpad=10)
plt.xticks(rotation=45)
ax = plt.gca()
ax.set_facecolor('white')
for spine in ['top', 'right']:
    ax.spines[spine].set_visible(False)
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 4))
sns.countplot(
    x='market_segment_type',
    hue='booking_status',
    data=df,
    palette=['#ab1636', '#3a7ca5'],
    edgecolor='white',
    linewidth=0.5
)
plt.title("Канал бронирования vs Статус брони", fontsize=14, fontweight='bold', pad=15)
plt.xlabel("Канал бронирования", fontsize=12, labelpad=10)
plt.ylabel("Количество бронирований", fontsize=12, labelpad=10)
plt.xticks(rotation=45)
plt.legend(title='Статус брони', title_fontsize=12, fontsize=11)
ax = plt.gca()
ax.set_facecolor('white')
for spine in ['top', 'right']:
    ax.spines[spine].set_visible(False)
plt.tight_layout()
plt.show()

print("\nПроцентное соотношение статусов по каналам бронирования:")
crosstab = pd.crosstab(
    index=df['market_segment_type'],
    columns=df['booking_status'],
    normalize='index'
).round(3) * 100

display(crosstab.style
        .set_caption("Соотношение статусов брони по каналам (в %)")
        .set_properties(**{'background-color': 'white', 'color': '#333333'})
        .format("{:.1f}%")
        .highlight_max(axis=1, color='#f26a8d'))

print("\n=== АНАЛИЗ КАТЕГОРИАЛЬНЫХ ПЕРЕМЕННЫХ ===")

print("Распределение статусов:")
print(df['booking_status'].value_counts())

plt.figure(figsize=(6, 6))
wedges, texts, autotexts = plt.pie(
    df['booking_status'].value_counts(),
    autopct='%1.1f%%',
    colors=['#3a7ca5', '#ab1636'],
    wedgeprops={'edgecolor': 'white', 'linewidth': 0.5},
    textprops={'fontsize': 12},
    startangle=90
)

plt.title("Доля отмен и подтверждений брони", fontsize=14, fontweight='bold', pad=20)
plt.legend(
    wedges,
    ['Не отменено', 'Отменено'],
    title='Статус брони',
    loc='upper right',
    bbox_to_anchor=(1, 0.9)
)
plt.tight_layout()
plt.show()
status_counts = df['booking_status'].value_counts(normalize=True).round(3) * 100
not_canceled = status_counts.iloc[0] if 'Не отменено' in status_counts else status_counts.iloc[1]
canceled = status_counts.iloc[1] if 'Не отменено' in status_counts else status_counts.iloc[0]
print(f"\nПроцентное соотношение:")
print(f"Подтверждено: {not_canceled}%")
print(f"Отменено: {canceled}%")

print("\n=== СОЗДАНИЕ И АНАЛИЗ НОВЫХ ПРИЗНАКОВ ===")

df['lenght_of_stay'] = df['no_of_week_nights'] + df['no_of_weekend_nights']
df['total_guests'] = df['no_of_adults'] + df['no_of_children']
df['type_of_accommodation'] = pd.cut(
    df['lenght_of_stay'],
    bins=[0, 2, 5, 100],
    labels=['short', 'middle', 'long']
)
df['group_type'] = pd.cut(
    df['total_guests'],
    bins=[0, 1, 2, 4, 100],
    labels=['one', 'pair', 'family', 'group']
)
df['booking_type'] = pd.cut(
    df['lead_time'],
    bins=[-1, 3, 30, 365],
    labels=['last moment', 'standard', 'early']
)
df['season'] = pd.cut(
    df['arrival_month'],
    bins=[0, 2, 5, 8, 11, 12],
    labels=['winter', 'spring', 'summer', 'autumn', 'winter'],
    ordered=False
)

print("\n=== ПРОВЕРКА СОЗДАННЫХ ПРИЗНАКОВ ===")
new_cat_cols = ['type_of_accommodation', 'group_type', 'booking_type', 'season']

for col in new_cat_cols:
    print(f"\n── Проверка признака: {col} ──")

    # 1. Статистика с числовыми значениями
    print("\nРаспределение значений (абсолютные и относительные частоты):")
    value_counts = df[col].value_counts(dropna=False)
    value_percents = df[col].value_counts(dropna=False, normalize=True).mul(100).round(1)
    display(pd.DataFrame({
        'Количество': value_counts,
        'Доля (%)': value_percents
    }))

    # 2. Визуализация с числовыми значениями на столбцах
    plt.figure(figsize=(10, 5))
    ax = df[col].value_counts().plot.bar(
        color='#ab1636',
        edgecolor='white',
        width=0.7
    )

    # Добавление числовых значений на столбцы
    for p in ax.patches:
        ax.annotate(f'{int(p.get_height())}\n({p.get_height()/len(df)*100:.1f}%)',
                   (p.get_x() + p.get_width() / 2., p.get_height()),
                   ha='center', va='center',
                   xytext=(0, 10),
                   textcoords='offset points',
                   fontsize=10)

    plt.title(f"Распределение: {col}", fontsize=14, pad=15)
    plt.xlabel("")
    plt.ylabel("Количество", fontsize=12)
    plt.xticks(rotation=45, fontsize=11)
    ax = plt.gca()
    ax.set_facecolor('white')
    for spine in ['top', 'right']:
        ax.spines[spine].set_visible(False)
    plt.tight_layout()
    plt.show()

# --- 2. Анализ выбросов для новых ЧИСЛОВЫХ признаков ---
num_new_cols = ['lenght_of_stay', 'total_guests']
for col in num_new_cols:
    print(f"\n── Анализ выбросов: {col} ──")

    # Статистика по числовому признаку
    print("\nОсновные статистики:")
    display(df[col].describe().to_frame('Значение'))

    plt.figure(figsize=(12, 5))

    # Гистограмма с плотностью
    plt.subplot(1, 2, 1)
    sns.histplot(
        x=df[col],
        color='#ab1636',
        kde=True,
        bins=30
    )
    plt.title(f"Распределение {col}", fontsize=12, pad=10)
    plt.xlabel(col, fontsize=10)
    plt.ylabel("Частота", fontsize=10)

    # Boxplot
    plt.subplot(1, 2, 2)
    sns.boxplot(
        x=df[col],
        color='#ab1636',
        width=0.4,
        flierprops=dict(marker='o', markersize=5, markerfacecolor='#3a7ca5')
    )
    plt.title(f"Выбросы: {col}", fontsize=12, pad=10)
    plt.xlabel("")
    plt.xticks(fontsize=10)

    plt.tight_layout()
    plt.show()

    q1, q3 = df[col].quantile([0.25, 0.75])
    iqr = q3 - q1
    lower, upper = q1 - 1.5*iqr, q3 + 1.5*iqr
    outliers = df[(df[col] < lower) | (df[col] > upper)]
    print(f"• Границы выбросов: [{lower:.1f}, {upper:.1f}]")
    print(f"• Найдено выбросов: {len(outliers)} ({len(outliers)/len(df)*100:.1f}%)")

# --- 3. Анализ КАТЕГОРИАЛЬНЫХ новых признаков ---
new_cat_columns = ['booking_type', 'season', 'type_of_accommodation', 'group_type']

for col in new_cat_columns:
    print(f"\n{'='*50}\nАнализ признака: {col}\n{'='*50}")

    # Таблица с распределением
    print("\nРаспределение значений (абсолютные и относительные частоты):")
    value_counts = df[col].value_counts(dropna=False)
    value_percents = df[col].value_counts(dropna=False, normalize=True).mul(100).round(1)
    display(pd.DataFrame({
        'Количество': value_counts,
        'Доля (%)': value_percents
    }))

    # Визуализация распределения
    plt.figure(figsize=(12, 6))
    ax = sns.countplot(
        x=col,
        data=df,
        order=df[col].value_counts().index,
        color='#ab1636',
        edgecolor='white',
        linewidth=0.5
    )

    # Добавление числовых значений на столбцы
    for p in ax.patches:
        ax.annotate(f'{int(p.get_height())}\n({p.get_height()/len(df)*100:.1f}%)',
                   (p.get_x() + p.get_width() / 2., p.get_height()),
                   ha='center', va='center',
                   xytext=(0, 10),
                   textcoords='offset points',
                   fontsize=10)

    plt.title(f"Распределение: {col}", fontsize=14, fontweight='bold', pad=15)
    plt.xlabel(col, fontsize=12, labelpad=10)
    plt.ylabel("Количество бронирований", fontsize=12, labelpad=10)
    plt.xticks(rotation=45)
    ax = plt.gca()
    ax.set_facecolor('white')
    for spine in ['top', 'right']:
        ax.spines[spine].set_visible(False)
    plt.tight_layout()
    plt.show()

    # Визуализация связи с целевой переменной
    plt.figure(figsize=(12, 6))
    ax = sns.countplot(
        x=col,
        hue='booking_status',
        data=df,
        palette=['#3a7ca5', '#ab1636'],
        edgecolor='white',
        linewidth=0.5
    )

    # Добавление числовых значений на столбцы
    for p in ax.patches:
        ax.annotate(f'{int(p.get_height())}',
                   (p.get_x() + p.get_width() / 2., p.get_height()),
                   ha='center', va='center',
                   xytext=(0, 5),
                   textcoords='offset points',
                   fontsize=9)

    plt.title(f"Влияние {col} на отмену брони", fontsize=14, fontweight='bold', pad=15)
    plt.xlabel(col, fontsize=12, labelpad=10)
    plt.ylabel("Количество бронирований", fontsize=12, labelpad=10)
    plt.xticks(rotation=45)
    plt.legend(title='Статус брони', title_fontsize=12, fontsize=11)
    ax = plt.gca()
    ax.set_facecolor('white')
    for spine in ['top', 'right']:
        ax.spines[spine].set_visible(False)
    plt.tight_layout()
    plt.show()

    # Таблица с процентным соотношением статусов
    print("\nПроцентное соотношение статусов бронирования:")
    crosstab = pd.crosstab(
        index=df[col],
        columns=df['booking_status'],
        normalize='index'
    ).round(3) * 100
    display(crosstab.style
            .set_caption(f"Статусы брони по категориям {col} (в %)")
            .set_properties(**{'background-color': 'white', 'color': '#333333'})
            .format("{:.1f}%"))

print("\n=== КОРРЕЛЯЦИОННЫЙ АНАЛИЗ ===")

plt.figure(figsize=(12, 8))
corr = df.select_dtypes(include=['number']).corr()
mask = np.triu(np.ones_like(corr, dtype=bool))
heatmap = sns.heatmap(
    corr,
    mask=mask,
    annot=True,
    cmap=['#3a7ca5', 'white', '#ab1636'],
    center=0,
    fmt=".2f",
    linewidths=.5,
    cbar_kws={'label': 'Уровень корреляции'}
)

plt.title("Корреляция числовых признаков", fontsize=16, fontweight='bold', pad=20)
heatmap.set_xticklabels(
    heatmap.get_xticklabels(),
    rotation=45,
    horizontalalignment='right'
)
heatmap.set_yticklabels(
    heatmap.get_yticklabels(),
    rotation=0
)

plt.tight_layout()
plt.show()

df.to_csv('hotel_new_features.csv', index=False)

df

df_new = pd.read_csv("hotel_new_features.csv")
df_new.head()

df_new.columns

df_new = df_new.drop(['Booking_ID'], axis=1)
df_new = df_new.drop(['arrival_year'], axis=1)
df_new

import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.feature_selection import VarianceThreshold, SelectKBest, f_classif, RFE
from sklearn.decomposition import PCA
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import seaborn as sns

# Разделение на признаки и целевую переменную
X = df_new.drop('booking_status', axis=1)
y = df_new['booking_status']

# Кодирование целевой переменной
le = LabelEncoder()
y_encoded = le.fit_transform(y)

df_new['booking_status'] = df_new['booking_status'].map({'Not_Canceled': 0, 'Canceled': 1})

df_new

## 1. Кодирование категориальных признаков

# Идентификация категориальных признаков
categorical_cols = X.select_dtypes(include=['object']).columns
numerical_cols = X.select_dtypes(exclude=['object']).columns

print("\nКатегориальные признаки:", categorical_cols.tolist())
print("Числовые признаки:", numerical_cols.tolist())

# Метод Label Encoding для категориальных признаков с небольшим количеством уникальных значений
label_cols = [col for col in categorical_cols if X[col].nunique() <= 5]
for col in label_cols:
    X[col] = LabelEncoder().fit_transform(X[col])

# Метод One-Hot Encoding для остальных категориальных признаков
ohe_cols = [col for col in categorical_cols if X[col].nunique() > 5]
X = pd.get_dummies(X, columns=ohe_cols, drop_first=True)

# Заполнение пропущенных значений (если есть)
X.fillna(X.mean(), inplace=True)

## 2. Отбор признаков
### 2.1. Метод на основе дисперсии
selector = VarianceThreshold(threshold=0.01)  # Удаляем признаки с дисперсией < 0.01
X_variance = selector.fit_transform(X)
selected_features_variance = X.columns[selector.get_support()]
print(f"Признаки после отбора по дисперсии: {len(selected_features_variance)} из {X.shape[1]}: ", selected_features_variance)

##2.2 Корреляционный анализ
numeric_features = df_new.select_dtypes(include=['int64', 'float64']).columns
correlation_matrix = df_new[numeric_features].corr()

# Визуализация
plt.figure(figsize=(12, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', center=0)
plt.title('Матрица корреляции числовых признаков')
plt.show()

# Удаляем сильно коррелирующие признаки
upper = correlation_matrix.where(np.triu(np.ones(correlation_matrix.shape), k=1).astype(bool))
to_drop = [column for column in upper.columns if any(upper[column] > 0.8)]
X_corr = X.drop(to_drop, axis=1)
print(f"Удалено {len(to_drop)} сильно коррелирующих признаков: ", to_drop)

### 2.3. Метод главных компонент (PCA)
# Масштабирование данных
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Применение PCA
pca = PCA()
X_pca = pca.fit_transform(X_scaled)

# Визуализация объясненной дисперсии
plt.figure(figsize=(10, 6))
plt.plot(np.cumsum(pca.explained_variance_ratio_))
plt.xlabel('Количество компонент')
plt.ylabel('Объясненная дисперсия')
plt.title('Кумулятивная объясненная дисперсия')
plt.grid()
plt.show()

# Выбираем количество компонент, объясняющих 95% дисперсии
n_components = np.argmax(np.cumsum(pca.explained_variance_ratio_) >= 0.95) + 1
print(f"Рекомендуемое количество компонент: {n_components}")

### 2.4. Методы обертывания (RFE)
# Разделение данных на train/test
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.3, random_state=42)

# Используем Random Forest в качестве модели для RFE
model = RandomForestClassifier(random_state=42)
rfe = RFE(estimator=model, n_features_to_select=15, step=1)
rfe.fit(X_train, y_train)

# Отобранные признаки
selected_features_rfe = X.columns[rfe.support_]
print("Лучшие признаки по RFE:", selected_features_rfe.tolist())

### 2.5. Методы вложения (Feature Importance)
model.fit(X_train, y_train)
importances = model.feature_importances_

# Сортируем признаки по важности
indices = np.argsort(importances)[::-1]
features = X.columns

# Визуализация важности признаков
plt.figure(figsize=(12, 8))
plt.title("Важность признаков (Random Forest)")
plt.bar(range(X.shape[1]), importances[indices], align="center")
plt.xticks(range(X.shape[1]), features[indices], rotation=90)
plt.xlim([-1, X.shape[1]])
plt.tight_layout()
plt.show()

# Выбираем топ-15 самых важных признаков
top_n = 15
selected_features_importance = features[indices][:top_n]
print(f"Топ-{top_n} важных признаков:", selected_features_importance.tolist())

## 3. Итоговый отбор признаков
# Объединяем результаты разных методов
final_features = set(selected_features_variance) & set(X_corr.columns) & set(selected_features_rfe) & set(selected_features_importance)
print(f"Итоговое количество отобранных признаков: {len(final_features)}")
print("Итоговые отобранные признаки:", final_features)

# Создаем новый датасет с отобранными признаками
X_final = X[list(final_features)]

X_final['booking_status'] = y_encoded
Final_features = X_final
Final_features

Final_features.to_csv('Final_features.csv', index=False)

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, precision_recall_curve, roc_curve, roc_auc_score, ConfusionMatrixDisplay, auc
from imblearn.over_sampling import SMOTE

# Загрузка и исследование данных
df = pd.read_csv('Final_features.csv')
print(df['booking_status'].value_counts())

# Разделение данных
X = df.drop('booking_status', axis=1)
y = df['booking_status']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=10, stratify=y)

# Масштабирование данных
scaler = StandardScaler()
scaled_X_train = scaler.fit_transform(X_train)
scaled_X_test = scaler.transform(X_test)

# Обработка дисбаланса классов
print("Баланс классов в y_train до обработки:", pd.Series(y_train).value_counts())
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(scaled_X_train, y_train)
print("Баланс классов в y_train после обработки:", pd.Series(y_train_resampled).value_counts())

# Обучение модели с кросс-валидацией и подбором параметров

# Используем GridSearchCV для подбора оптимальных параметров
param_grid = {'solver': ['liblinear', 'lbfgs', 'newton-cg', 'sag', 'saga']}
grid_model = GridSearchCV(LogisticRegression(random_state=42),
                           param_grid,
                           scoring='recall',
                           cv=5,
                           verbose=0)

grid_model.fit(X_train_resampled, y_train_resampled)

print("Лучшие параметры:", grid_model.best_params_)
best_log_model = grid_model.best_estimator_

# Оценка модели
y_pred = best_log_model.predict(scaled_X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

disp = ConfusionMatrixDisplay(confusion_matrix=confusion_matrix(y_test, y_pred),
                               display_labels=best_log_model.classes_)
disp.plot()
plt.show()


print("Classification Report:\n", classification_report(y_test, y_pred))

# Получение вероятностей предсказаний
y_proba = best_log_model.predict_proba(scaled_X_test)[:, 1]  # Вероятности для класса 1

# Выбор порога
threshold = 0.6

# Предсказания на основе порога:
y_pred_threshold = (y_proba > threshold).astype(int)

# Оценка модели с новым порогом:
print("\nОценка модели с новым порогом ({}):".format(threshold))
print("Accuracy:", accuracy_score(y_test, y_pred_threshold))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_threshold))

disp_threshold = ConfusionMatrixDisplay(confusion_matrix=confusion_matrix(y_test, y_pred_threshold),
                               display_labels=best_log_model.classes_)
disp_threshold.plot()
plt.show()

print("Classification Report:\n", classification_report(y_test, y_pred_threshold))

fpr_threshold, tpr_threshold, thresholds_roc_threshold = roc_curve(y_test, y_proba) #y_proba нужно для вычисления auc_roc
roc_auc_threshold = roc_auc_score(y_test, y_proba) #y_proba нужно для вычисления auc_roc


plt.plot(fpr_threshold, tpr_threshold, label=f'ROC AUC (Threshold = {threshold:.2f}) = {roc_auc_threshold:.2f}')
plt.plot([0, 1], [0, 1], 'k--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve (Custom Threshold)')
plt.legend()
plt.show()

y_proba = best_log_model.predict_proba(scaled_X_test)[:, 1]  # Вероятности для класса 1
y_proba_class0 = 1-y_proba # Вероятности для класса 0

# ROC AUC
fpr, tpr, thresholds_roc = roc_curve(y_test, y_proba_class0, pos_label = 0)
roc_auc = roc_auc_score(y_test, y_proba)

plt.plot(fpr, tpr, label=f'ROC AUC = {roc_auc:.2f}')
plt.plot([0, 1], [0, 1], 'k--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve')
plt.legend()
plt.show()

# Получение вероятностей принадлежности к классам для тестовых данных
proba = best_log_model.predict_proba(scaled_X_test)

# Создание DataFrame с вероятностями и фактическими значениями
proba_df = pd.DataFrame(proba, columns=['Probability_Class_0', 'Probability_Class_1'])
proba_df['Actual_Class'] = y_test.values
proba_df['Predicted_Class'] = y_pred_threshold

# Вывод DataFrame с вероятностями
print("\nВероятности принадлежности к классам для тестовых данных:")
print(proba_df.head())

# Пример доступа к вероятностям для конкретного экземпляра (например, первого)
instance_index = 0
probability_of_booking = proba_df['Probability_Class_1'][instance_index]
print(f"\nВероятность бронирования для экземпляра {instance_index}: {probability_of_booking:.4f}")